config/routes.rb
Socialapps::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :pages

  get 'admin' => 'pages#admin', as: :admin

  root 'pages#index'
  post '/' => 'pages#index' #set root here too (fb shit)

  get 'tab' => 'pages#tab', as: :tab

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

    # acts_as_voter

    def self.find_for_facebook_oauth(auth)
  	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  	    user.provider = auth.provider
  	    user.uid = auth.uid
  	    user.email = auth.info.email if auth.info.email
  	    user.password = Devise.friendly_token[0,20]
  	    user.name = auth.info.name
  	    user.image = auth.info.image
  	    user.link = auth.extra.raw_info.link
  	    user.oauth_token = auth.credentials.token
  	    user.oauth_token_expires_at = auth.credentials.expires_at
  	    user.save!
  	  end
  	end

	def self.new_with_session(params, session)
		super.tap do |user|
		  if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
		    #user.email = data["email"] if user.email.blank?
		  end
		end
	end

  def email_required?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :null_session
  skip_before_filter :verify_authenticity_token

  after_filter :allow_iframe

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end

private
  def allow_iframe
      response.headers['X-Frame-Options'] = "ALLOW-FROM https://www.facebook.com"
  end

  def mobile_agent?
    request.user_agent =~ /Mobile|webOS/
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def tab
  end

  def admin
    @users = User.all.order('id DESC')
    render layout: "admin"
  end

private
  def is_admin?
    if user_signed_in?
      current_user.try(:admin?)
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update]
  before_action :authenticate_user!, except: [:show]

  def edit
    @user = current_user
  end

  def start
    current_user.update_attribute :started, true
    redirect_to root_url
  end

  def update
    if @user.update(user_params)
      @user.save
				redirect_to root_url, notice: 'OK'
    else
				render action: 'edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:phone, :name, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_admin?
  	if user_signed_in?
  		current_user.try(:admin?)
  	end
  end

  def app_title
    # Mainlu for <title> tag
    "_app_title_"
  end

  def organizer
    # mentioned in footer disclaimer
    "_organizer_"
  end

  def app_domain
    if Rails.env.development? then "_app_name_.dev" else "_app_name_.herokuapp.com" end
  end

end

app/views/layouts/_admin_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Admin", admin_path, class: "btn btn-default" %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><%= link_to destroy_user_session_path, :method => :delete, class: "btn btn-default pull-right" do %><%=t 'sign_out' %><%end%></li>
    </ul>

  </section>
</nav>


<div class="container">

  <div class="row">
    <div class="small-12">
      <% flash.each do |name, message| %>
        <br>
        <div data-alert class="alert-box">
          <%= content_tag :div, message, :id => "flash_#{name}", :class => "notice" %>
          <a href="#" class="close">&times;</a>
        </div>
      <% end %>

    </div>
  </div>


</div>

app/views/layouts/_footer.html.erb
<div class="row">
	<div class="small-12 column footer">
			<p>Această aplicație nu este in niciun fel sponsorizată, sprijinită, administrată sau asociată cu <a href="https://facebook.com" target="_blank">Facebook</a>. Prin înregistrarea în aplicație, informațiile tale vor fi prelucrate de către <%= link_to organizer, "https://facebook.com/#{ ENV['FB_PAGE'] }", target: "_blank" %> și sub nicio forma de către <a href="https://facebook.com" target="_blank">Facebook</a>. Informația oferită de către Dvs. în această aplicație va fi folosită doar ca să asigure o buna funcționare.</p>


			<p>
				<% if user_signed_in? %>
					Signed in as <b><%= current_user.name %></b> [<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>]
				<%end%>
			</p>
	</div>
</div>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV[GOOGLE_ANALYTICS] %>', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_nav.html.erb
<div class="row nav-buttons" style="width:600px; margin:0 auto;">
	<div class="small-4 column">
	<%= link_to 'Regulament', '/regulament.pdf', class: 'button radius', target: "_blank" %>
	</div>
	<div class="small-4 text-center column">
	<%= link_to 'Participanți', cards_path, class: 'button radius' %>
	</div>


	<div class="small-4 text-right column">
	<% if user_signed_in? && current_user.cards[0] %>
	<%= link_to 'Poza ta', card_path(current_user.cards.last), class: 'button radius' %>
	<%else%>
	<%= link_to 'Participă', new_card_path, class: 'button radius' %>
	<%end%>

	</div>
</div>

app/views/layouts/_show_nav.html.erb
<div class="row nav-buttons right">
	<%= link_to 'Participanți', cards_path, class: 'button radius' %>
	<br>
	<a href="https://www.facebook.com/dialog/share?app_id=<%= ENV['FB_APP_ID'] %>&display=popup&href=<%= card_url(@card) %>&redirect_uri=<%= card_url(@card) %>" target="_blank" class="button radius">Distribuie</a>
	<br>
	<% if user_signed_in? && current_user.cards[0] %>
		<%= link_to 'Editează', polish_path(@card), class: 'button radius' %>
	<%else%>
		<%= link_to 'Participă', new_card_path, class: 'button radius' %>
	<%end%>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= app_title %></title>

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta property="fb:app_id" content="<%= ENV['FB_APP_ID'] %>"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta property="og:image" content="https://<%= app_domain %>/og.jpg">
  <%= javascript_include_tag "vendor/modernizr" %>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= render :partial => 'layouts/ga' if Rails.env == 'production' %>


</head>
<body class="<% if current_page?(root_url) %>index<%end%>">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= ENV['FB_APP_ID'] %>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<%= ENV['FB_APP_ID'] %>',
      status     : true,
      xfbml      : true
    });

    FB.Canvas.setAutoGrow();
    FB.Canvas.scrollTo(0,0);
  };
</script>



<div class="clouds">

  <div class="fbtab">
    <div class="row">
      <div class="small-12 column">
        <%= yield %>
      </div>
    </div>
  </div>

</div>

  <%= render partial: "layouts/footer" %>



</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= app_title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta property="fb:app_id" content="<%= ENV['FB_APP_ID'] %>"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta property="og:image" content="https://<%= app_domain %>/og.jpg">
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= render :partial => 'layouts/ga' if Rails.env == 'production' %>
</head>
<body>
<div id="fb-root"></div>
<script>

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<%= ENV['FB_APP_ID'] %>',
      xfbml      : true,
      version    : 'v2.5'
    });
    FB.Canvas.setAutoGrow();
    FB.Canvas.scrollTo(0,0);
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<% if !is_admin? %>
  <script type="text/javascript">
    var url = top.location.href

      if ( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {

    } else {
      if ( url.match(/heroku/) ) {
          top.location.href = "https://facebook.com/" + "<%= ENV['FB_PAGE'] %>" + "/app_" + "<%= ENV['FB_APP_ID'] %>"
      }
    }
  </script>
<%end%>

  <div class="row">
    <div class="small-12 column">
      <%= yield %>
    </div>
  </div>

  <%= render partial: "layouts/footer" %>

</body>
</html>

app/views/pages/admin.html.erb
<% if is_admin? %>

<br><br> 

	<table style="width:100%;" class="table">
		<tr>
			<th>Nume</th>
			<th>*</th>
			<th>*</th>
			<th>*</th>
		</tr>
		<% @cards.each do |c| %>
			<tr class="<%= c.approved ? 'approved' : 'disapproved'  %>">
				<td><%= link_to c do %>
					<%= image_tag c.image.url(:thumb) %> <%= link_to c.user.name, c.user.link %>
					<%end%>
				</td>
				<td>
					<% if c.approved %>
					<%= link_to 'disapprove', disapprove_path(c), style: 'opacity: 0.3' %>
					<%else%>
					<%= link_to 'approve', approve_path(c) %>
					<%end%>
				</td>
				<td>
					<%= link_to 'edit', polish_path(c) %>
				</td>
				<td>
					<%= link_to 'originalul', c.image.url %>
				</td>
			</tr>
		<%end%>
	</table>
<%else%>
you are not an admin
<%end%>

app/views/pages/index.html.erb
<div class="frontpage">

	<div class="row">
	  <div class="small-12 column">
		<a href="#" class="button round">Participă</a>
	  </div>
	</div>

</div>

app/views/users/edit.html.erb
<h1 class="text-center"><span class="red">ULTIMUL PAS!</span><br><span style="font-size:20px;">Completează ancheta cu datele tale personale*</span></h1>
<p class="info">*Datele personale vor fi păstrate strict confidențial</p>
<div class="row">
  <div class="col-sm-6">
    <%= form_for(@user) do |f| %>

      <div class="field">
        <%= f.label :name, "Nume" %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :phone, "Telefon*" %>
        <%= f.phone_field :phone %>
      </div>

      <div class="field">
        <%= f.label :email, "E-mail" %>
        <%= f.email_field :email %>
      </div>

      <br>
      <div class="actions text-center">
        <%= f.submit "", class: "btn-image btn-finalizeaza" %>
      </div>
    <% end %>
  </div>
  <div class="col-sm-6">
    <div class="row">
      <div class="col-md-6 column">
        <h3 class="name-on-card m"><%= current_user.name %></h3>
        <div class="card-content-m"></div>
        <div class="img-preview img-preview-m"></div>
      </div>
    </div>

  </div>
</div>